In [1]:
import numpy as np

In [2]:
#can also define the data type
#a=np.array([1,4,7],dtype='int16')
a=np.array([1,4,7])

In [3]:
b=np.array([1,5,9])

In [4]:
print(a*b)

[ 1 20 63]


In [5]:
#gives dimension
a.ndim

1

In [6]:
c=np.array([[1,4,7],[4,6,8]])

In [7]:
c.ndim

2

In [8]:
#get shape
c.shape

(2, 3)

In [9]:
a.shape

(3,)

In [10]:
#gives data type
a.dtype

dtype('int64')

In [11]:
#get the size of each data 
a.itemsize

8

In [12]:
#get total size
a.nbytes

24

In [13]:
c.nbytes

48

In [15]:
d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
#get the specific row
d[0,:]

array([1, 2, 3, 4, 5])

In [17]:
#get the specific column
d[:,3]

array([4, 9])

In [18]:
#access the speific element 
d[1,3]

9

In [21]:
 #little more complex..[startIndex:EndIndex:StepSize]
d[0,1:5:2]

array([2, 4])

In [25]:
#change the column elements
d[:,2]=12
print(d)

#with given shape 
d[:,2]=[3,0]
print(d)

[[ 1  2 12  4  5]
 [ 6  7 12  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  0  9 10]]


In [30]:
#all zeros 
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
#all ones
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [34]:
#any other number....(shape,number)
np.full((2,3,3),23)

array([[[23, 23, 23],
        [23, 23, 23],
        [23, 23, 23]],

       [[23, 23, 23],
        [23, 23, 23],
        [23, 23, 23]]])

In [36]:
#change all elements to a number(full_like)
np.full_like(c,12)

array([[12, 12, 12],
       [12, 12, 12]])

In [37]:
#random number(shape)
np.random.rand(3,3)

array([[0.91846903, 0.4372216 , 0.58168411],
       [0.78094552, 0.86165423, 0.25457008],
       [0.10889144, 0.76555888, 0.5309405 ]])

In [42]:
#random interger value with some range(range,shape)->range(start,end)-->exclusive end
np.random.randint(8,10,size=(3,3))

array([[9, 9, 8],
       [8, 8, 8],
       [8, 9, 9]])

In [40]:
#identity matrix,,(length)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
#repeat the array(array,no of repeats,axis=0(default))
arr=np.array([[1,2,3]])
r1=np.repeat(arr,4,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [61]:
ar=np.ones((5,5))
#print(ar)
ar[1:-1,1:-1]=0
ar[2,2]=9
print(ar)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be carefull while copying the array

In [64]:
a=np.array([1,3,4])

b=a
b[0]=12
print(a)

[12  3  4]


In [65]:
#to remove the issue ..make copy of that array
a=np.array([2,5,7])
b=a.copy()
b[0]=31
print(a)
print(b)

[2 5 7]
[31  5  7]


# Mathematics


In [66]:
#whatever we will do,,,will effect all the elements 
a=np.array([3,5,6,7,8])
a*2



array([ 6, 10, 12, 14, 16])

In [67]:
print(a**2)

[ 9 25 36 49 64]


#Statistics


In [68]:
states=np.array([[1,2,4],[3,5,7]])
states


array([[1, 2, 4],
       [3, 5, 7]])

In [69]:
np.min(states)

1

np.max(states)

In [71]:
np.sum(states)

22

# Reorganazing the array


In [77]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

#make it 4,2 shape
after=before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
